[package]
name = "mhfwupdater"
version = "0.1.0"
edition = "2024"
description = "Firmware updater for microHAM USB devices"
license = "GPL-2.0-only"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
env_logger = { version = "0.11", default-features = false }
log = "0.4"
serialport = { version = "4.8", default-features = false }
